server.port=8081

user.service.message=User Service is running from COnfig Server
spring.application.name=USER-SERVICE

management.tracing.sampling.probability = 1.0
management.zipkin.tracing.endpoint=https://localhost:9411/api/v2/spans

spring.datasource.username=root
spring.datasource.password={cipher}2a05b5680a9f5d03b655f57a2fd193b6595886ce8f46f9400e23b67758c9c9e1
